#CodeAssist project settings
#Tue Sep 29 00:02:18 GMT+03:00 2026
tree.expanded.Project=module\:app\nworkspace\npkg\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/notebk/app/src/main/kotlin/com/ahd/notebk\nbuild-outputs\:app\nroot\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/notebk/app/src/main/kotlin\nroot\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/notebk/app/src/main/res
